### ISSUE TITLE
Trying to delete a tag notifier always deletes the last tag notifier in the list

### ISSUE THREAD

**Issue by NIEKnox** [hecksadecimal/birdwatcher#1]
How to replicate:
1. Make two or more tag notifiers
2. Try and delete any tag notifier other than the last one in the list

It will always delete the last tag in the list, rather than the one that was clicked.

**Comment by hecksadecimal** [comment]
Thanks for the report. I'll look into this and implement a fix soon.

**Comment by hecksadecimal** [comment]
@NIEKnox 
The fix for this is available in [v1.0.1](https://github.com/hecksadecimal/birdwatcher/releases/tag/v1.0.1)
